Repository TeamSaltshaker/DamDam, pull requests merged in 2025-09, with the labels that each got.

#703 ParseResultType 도메인으로 이동
  Clipster/Clipster.xcodeproj/project.pbxproj
  Clipster/Clipster/Domain/Model/VO/ParseResultType.swift
  Clipster/Clipster/Domain/Protocol/UseCase/URL/ParseURLUseCase.swift
  Clipster/Clipster/Domain/UseCase/URL/DefaultParseURLUseCase.swift
  Clipster/Clipster/Presentation/Scene/EditClip/Reactor/EditClipReactor.swift
  Clipster/ClipsterTests/Domain/UseCase/Clip/SearchClipsUseCaseTests.swift
  Clipster/ClipsterTests/Domain/UseCase/Clip/SortClipsUseCaseTests.swift
  Clipster/ClipsterTests/Domain/UseCase/Folder/FilterSubfoldersUseCaseTests.swift
  Clipster/ClipsterTests/Domain/UseCase/Folder/FindFolderPathUseCaseTests.swift
  Clipster/ClipsterTests/Domain/UseCase/Folder/SearchFoldersUseCaseTests.swift
  Clipster/ClipsterTests/Domain/UseCase/Folder/SortFoldersUseCaseTests.swift
  Clipster/ClipsterTests/Domain/UseCase/URL/ParseURLUseCaseTests.swift
  Clipster/ClipsterTests/Presentation/Mock/UseCase/Auth/MockLoginUseCase.swift
  Clipster/ClipsterTests/Presentation/Mock/UseCase/Clip/MockFetchClipUseCase.swift
  Clipster/ClipsterTests/Presentation/Mock/UseCase/Clip/MockFetchTopLevelClipsUseCase.swift
  Clipster/ClipsterTests/Presentation/Mock/UseCase/Clip/MockFetchUnvisitedClipsUseCase.swift
  Clipster/ClipsterTests/Presentation/Mock/UseCase/Folder/MockFetchFolderUseCase.swift
  Clipster/ClipsterTests/Presentation/Mock/UseCase/Folder/MockFetchTopLevelFoldersUseCase.swift
  Clipster/ClipsterTests/Presentation/Mock/UseCase/URL/MockParseURLUseCase.swift
  Clipster/ClipsterTests/Presentation/Mock/UseCase/User/MockFetchCurrentUserUseCase.swift
  Clipster/ClipsterTests/Presentation/Mock/UseCase/User/MockUpdateNicknameUseCase.swift
  Clipster/ClipsterTests/Presentation/Reactor/ClipDetailReactorTests.swift
  Clipster/ClipsterTests/Presentation/Reactor/EditClipReactorTests.swift
  Clipster/ClipsterTests/Presentation/Reactor/EditFolderReactorTests.swift
  Clipster/ClipsterTests/Presentation/Reactor/FolderReactorTests.swift
  Clipster/ClipsterTests/Presentation/Reactor/FolderSelectorReactorTests.swift
  Clipster/ClipsterTests/Presentation/Reactor/HomeReactorTests.swift
  Clipster/ClipsterTests/Presentation/Reactor/MyPageReactorTests.swift
  Clipster/ClipsterTests/Presentation/Reactor/SearchReactorTests.swift
  Clipster/ClipsterTests/Presentation/Reactor/ShareReactorTests.swift
  Clipster/ClipsterTests/Presentation/Reactor/UnvisitedClipListReactorTests.swift
  Clipster/ClipsterTests/Presentation/Stub/Entity/StubClip.swift
  Clipster/ClipsterTests/Presentation/Stub/Entity/StubFolder.swift
  Clipster/ClipsterTests/Presentation/Stub/Entity/StubURLMetadata.swift
  Clipster/ClipsterTests/Presentation/Stub/Entity/StubUser.swift
  Clipster/ShareExtension/Reactor/ShareReactor.swift
Labels: refactor, test

#711 Folder, Clip Storage의 비즈니스 로직을 Repository로 이동
  Clipster/Clipster/Data/Persistence/DefaultClipStorage.swift
  Clipster/Clipster/Data/Persistence/DefaultFolderStorage.swift
  Clipster/Clipster/Data/Protocol/Persistence/ClipStorage.swift
  Clipster/Clipster/Data/Protocol/Persistence/FolderStorage.swift
  Clipster/Clipster/Data/Repository/Clip/DefaultClipRepository.swift
  Clipster/Clipster/Data/Repository/Folder/DefaultFolderRepository.swift
Labels: refactor

#709 탭바VC 코드 정리 및 Pop to Root 처리
  Clipster/Clipster/Presentation/Coordinator/TabBar/TabBarCoordinator.swift
  Clipster/Clipster/Presentation/Scene/TabBar/SubView/TabBarView.swift
  Clipster/Clipster/Presentation/Scene/TabBar/TabBarMode.swift
  Clipster/Clipster/Presentation/Scene/TabBar/TabItem.swift
  Clipster/Clipster/Presentation/Scene/TabBar/ViewController/TabBarController.swift
Labels: feat, refactor

#713 extractURLUseCase 테스트 코드 작성
  Clipster/Clipster/App/DIContainer/DIContainer.swift
  Clipster/Clipster/Domain/Protocol/UseCase/Pasteboard/ExtractURLUseCase.swift
  Clipster/Clipster/Domain/UseCase/Pasteboard/DefaultExtractURLUseCase.swift
  Clipster/Clipster/Presentation/Scene/EditClip/Reactor/EditClipReactor.swift
  Clipster/ClipsterTests/Domain/Stub/Repository/Pasteboard/StubPasteboardRepository.swift
  Clipster/ClipsterTests/Domain/Stub/Repository/URL/StubURLRepository.swift
  Clipster/ClipsterTests/Domain/UseCase/Pasteboard/ExtractURLUseCaseTests.swift
  Clipster/ClipsterTests/Presentation/Mock/UseCase/Pasteboard/MockExtractURLUseCase.swift
  Clipster/ClipsterTests/Presentation/Reactor/EditClipReactorTests.swift
Labels: fix, test

#714 v1.2.4 릴리즈
  Clipster/Clipster.xcodeproj/project.pbxproj
Labels: chore

#717 검색 화면 진입 시, 키보드 자동 포커싱 기능 제거
  Clipster/Clipster/Presentation/Scene/Search/ViewController/SearchViewController.swift
Labels: feat
