Repository TeamSaltshaker/DamDam, pull requests merged in 2025-06, with the labels that each got.

#17 [Feat/#10] CoreDataStack 구성
  Clipster/Clipster.xcodeproj/project.pbxproj
  Clipster/Clipster/App/Clipster.entitlements
  Clipster/Clipster/Data/Persistence/CoreDataStack.swift
Labels: feature

#27 [Feat/#11] CoreData 모델 설계
  Clipster/Clipster/Data/Model/ClipEntity.swift
  Clipster/Clipster/Data/Model/Clipster.xcdatamodeld/Clipster.xcdatamodel/contents
  Clipster/Clipster/Data/Model/FolderEntity.swift
  Clipster/Clipster/Data/Model/URLMetadataEntity.swift
  Clipster/Clipster/Domain/Model/Clip.swift
  Clipster/Clipster/Domain/Model/Folder.swift
  Clipster/Clipster/Domain/Model/URLMetadata.swift
Labels: feature

#21 [Feat/#20] 앱 라이트 모드 고정
  Clipster/Clipster/App/Derived/Info.plist
  Clipster/Clipster/App/Source/SceneDelegate.swift
Labels: feature

#34 [Feat] 컨벤션에 맞게 코드 수정
  Clipster/Clipster/App/Source/SceneDelegate.swift
  Clipster/Clipster/Data/Error/CoreDataError.swift
  Clipster/Clipster/Data/Persistence/DefaultClipStorage.swift
  Clipster/Clipster/Data/Protocol/Persistence/ClipStorage.swift
  Clipster/Clipster/Data/Repository/DefaultClipRepository.swift
  Clipster/Clipster/Domain/Protocol/Repository/ClipRepository.swift
  Clipster/Clipster/Domain/Protocol/UseCase/FetchClipUseCase.swift
  Clipster/Clipster/Domain/UseCase/Clip/DefaultFetchClipUseCase.swift
  Clipster/Clipster/Presentation/Model/ClipDisplay.swift
  Clipster/Clipster/Presentation/Scene/Home/ViewModel/HomeViewModel.swift
Labels: refactor

#39 [Feat] URLMetadataStackView 구현
  Clipster/Clipster/Presentation/Model/URLMetadataDisplay.swift
  Clipster/Clipster/Presentation/Scene/Common/StackView/URLMetadataStackView.swift
Labels: feature

#37 [Feat] EditFolderViewModel 설계
  Clipster/Clipster/Presentation/Scene/EditFolder/ViewModel/EditFolderViewModel.swift
Labels: feature

#38 [Feat] EditFolder UI 구현
  Clipster/Clipster/Presentation/Scene/EditFolder/Subview/Button/EditFolderBackButton.swift
  Clipster/Clipster/Presentation/Scene/EditFolder/Subview/Button/EditFolderSaveButton.swift
  Clipster/Clipster/Presentation/Scene/EditFolder/Subview/TextField/EditFolderTextField.swift
  Clipster/Clipster/Presentation/Scene/EditFolder/Subview/View/EditFolderView.swift
  Clipster/Clipster/Presentation/Scene/EditFolder/ViewController/EditFolderViewController.swift
Labels: feature

#55 [Feat] EditClipViewModel 구현
  Clipster/Clipster/Presentation/Scene/Common/StackView/URLMetadataStackView.swift
  Clipster/Clipster/Presentation/Scene/EditClip/Subview/View/EditClipView.swift
  Clipster/Clipster/Presentation/Scene/EditClip/ViewModel/EditClipViewModel.swift
  Clipster/Clipster/Presentation/Scene/EditClip/ViewModel/ViewModel.swift
Labels: feature

#56 [Feat] EditClipView 바인딩
  Clipster/Clipster/Presentation/Scene/EditClip/ViewController/EditClipViewController.swift
  Clipster/Clipster/Presentation/Scene/EditClip/ViewModel/EditClipViewModel.swift
Labels: feature

#82 [Feat] URLMetadata 파싱 구현
  Clipster/Clipster/Data/DTO/ParsedURLMetadataDTO.swift
  Clipster/Clipster/Data/Repository/URLMetadata/DefaultURLMetadataRepository.swift
  Clipster/Clipster/Domain/Entity/ParsedURLMetadata.swift
  Clipster/Clipster/Domain/Protocol/Repository/URLMetadata/URLMetadataRepository.swift
  Clipster/Clipster/Domain/Protocol/UseCase/URLMetadata/ParseURLMetadataUseCase.swift
  Clipster/Clipster/Domain/UseCase/URLMetadata/DefaultParseURLMetadataUseCase.swift
  Clipster/Clipster/Presentation/Model/URLMetadataDisplay.swift
Labels: feature

#81 feat: LicensePlist를 사용하여 설정에 오픈소스 라이선스 명시
  Clipster/Clipster/App/Derived/Settings.bundle/License.latest_result.txt
  Clipster/Clipster/App/Derived/Settings.bundle/License.plist
  Clipster/Clipster/App/Derived/Settings.bundle/License/Alamofire.plist
  Clipster/Clipster/App/Derived/Settings.bundle/License/Kingfisher.plist
  Clipster/Clipster/App/Derived/Settings.bundle/License/RxSwift.plist
  Clipster/Clipster/App/Derived/Settings.bundle/License/SnapKit.plist
  Clipster/Clipster/App/Derived/Settings.bundle/Root.plist
  Clipster/Clipster/App/Derived/Settings.bundle/en.lproj/Root.strings
Labels: feature

#87 [Feat] EditClipView UI 바인딩
  Clipster/Clipster/Presentation/Scene/Common/StackView/URLMetadataStackView.swift
  Clipster/Clipster/Presentation/Scene/EditClip/Subview/StackView/URLValidationStackView.swift
  Clipster/Clipster/Presentation/Scene/EditClip/Subview/View/EditClipView.swift
  Clipster/Clipster/Presentation/Scene/EditClip/ViewController/EditClipViewController.swift
  Clipster/Clipster/Presentation/Scene/EditClip/ViewModel/EditClipViewModel.swift
  Clipster/Clipster/Presentation/Util/Extension/ViewController+Extension.swift
Labels: feature

#95 [Feat] Section Header View 전체보기 버튼 추가 및 바인딩
  Clipster/Clipster/Presentation/Scene/Common/Cell/SectionHeaderView.swift
  Clipster/Clipster/Presentation/Scene/Home/Subview/View/HomeView.swift
  Clipster/Clipster/Presentation/Scene/Home/ViewController/HomeViewController.swift
  Clipster/Clipster/Presentation/Scene/Home/ViewModel/HomeViewModel.swift
  Clipster/Clipster/Presentation/Scene/UnvisitedClipList/ViewController/UnvisitedClipListViewController.swift
Labels: feature

#99 [Feat] 클립 수정 버튼으로 EditClipView 진입 가능하도록 수정
  Clipster/Clipster/Presentation/Scene/EditClip/ViewModel/EditClipViewModel.swift
Labels: feature

#101 [Feat] CellDisplay 스키마 변경
  Clipster/Clipster/Presentation/Model/ClipCellDisplay.swift
  Clipster/Clipster/Presentation/Model/FolderCellDisplay.swift
  Clipster/Clipster/Presentation/Scene/Home/ViewModel/HomeViewModel.swift
  Clipster/Clipster/Presentation/Scene/UnvisitedClipList/ViewController/UnvisitedClipListViewController.swift
  Clipster/Clipster/Presentation/Util/Mapper/CellDisplayMapper.swift
Labels: feature

#107 [Feat] 내비게이션 공통 컴포넌트
  Clipster/Clipster/Presentation/Scene/Common/Button/BackButton.swift
  Clipster/Clipster/Presentation/Scene/Common/Button/DeleteButton.swift
  Clipster/Clipster/Presentation/Scene/Common/Button/SaveButton.swift
  Clipster/Clipster/Presentation/Scene/Common/View/BackButtonView.swift
Labels: feature, refactor

#111 [Feat] 폴더 공통 컴포넌트 구현
  Clipster/Clipster/Presentation/Scene/Common/View/FolderRowView.swift
Labels: feature

#114 [Feat] Home화면에서 사용되는 UseCase 로직 구현
  Clipster/Clipster/App/Source/SceneDelegate.swift
  Clipster/Clipster/Domain/Protocol/UseCase/Folder/FetchTopLevelFoldersUseCase.swift
  Clipster/Clipster/Domain/UseCase/Clip/DefaultFetchUnvisitedClipUseCase.swift
  Clipster/Clipster/Domain/UseCase/Folder/DefaultDeleteFolderUseCase.swift
  Clipster/Clipster/Domain/UseCase/Folder/DefaultFetchTopLevelFoldersUseCase.swift
  Clipster/Clipster/Presentation/Scene/Home/ViewController/HomeViewController.swift
  Clipster/Clipster/Presentation/Scene/Home/ViewModel/HomeViewModel.swift
Labels: feature

#117 [Feat] 폴더 추가 화면 디자인 반영
  Clipster/Clipster/Presentation/Scene/EditFolder/Subview/Button/EditFolderBackButton.swift
  Clipster/Clipster/Presentation/Scene/EditFolder/Subview/Button/EditFolderSaveButton.swift
  Clipster/Clipster/Presentation/Scene/EditFolder/Subview/TextField/EditFolderTextField.swift
  Clipster/Clipster/Presentation/Scene/EditFolder/Subview/View/EditFolderView.swift
  Clipster/Clipster/Presentation/Scene/EditFolder/ViewController/EditFolderViewController.swift
Labels: feature

#118 [Feat] DIContainer 구현
  Clipster/Clipster/App/DIContainer/DIContainer.swift
  Clipster/Clipster/App/Source/SceneDelegate.swift
  Clipster/Clipster/Domain/UseCase/URLMetadata/DefaultParseURLMetadataUseCase.swift
  Clipster/Clipster/Domain/UseCase/URLValidation/DefaultCheckVaildityUseCase.swift
Labels: feature

#120 [Feat] 폴더 선택 UI 구현
  Clipster/Clipster/Presentation/Scene/Common/Button/BackButton.swift
  Clipster/Clipster/Presentation/Scene/Common/Button/SelectButton.swift
  Clipster/Clipster/Presentation/Scene/FolderSelector/Cell/FolderSelectorCell.swift
  Clipster/Clipster/Presentation/Scene/FolderSelector/Subview/View/FolderSelectorNavigationView.swift
  Clipster/Clipster/Presentation/Scene/FolderSelector/Subview/View/FolderSelectorView.swift
  Clipster/Clipster/Presentation/Scene/FolderSelector/ViewController/FolderSelectorViewController.swift
  Clipster/Clipster/Presentation/Util/Extension/UITableViewCell+Extension.swift
Labels: feature

#121 [Feat] 폴더 선택 상태 정의
  Clipster/Clipster/Presentation/Scene/FolderSelector/ViewModel/FolderSelectorViewModel.swift
Labels: feature

#127 [Feat] FolderView UI 구현
  Clipster/Clipster/Presentation/Scene/Folder/Subview/View/FolderView.swift
  Clipster/Clipster/Presentation/Scene/Folder/ViewController/FolderViewController.swift
  Clipster/Clipster/Presentation/Scene/Folder/ViewModel/FolderViewModel.swift
Labels: feature

#132 [Feat] 각 VC에 DIContainer 구현사항 적용
  Clipster/Clipster/App/DIContainer/DIContainer.swift
  Clipster/Clipster/App/Source/SceneDelegate.swift
  Clipster/Clipster/Presentation/Scene/ClipDetail/ViewController/ClipDetailViewController.swift
  Clipster/Clipster/Presentation/Scene/EditClip/ViewController/EditClipViewController.swift
  Clipster/Clipster/Presentation/Scene/EditFolder/ViewController/EditFolderViewController.swift
  Clipster/Clipster/Presentation/Scene/Folder/ViewController/FolderViewController.swift
  Clipster/Clipster/Presentation/Scene/FolderSelector/ViewController/FolderSelectorViewController.swift
  Clipster/Clipster/Presentation/Scene/Home/ViewController/HomeViewController.swift
  Clipster/Clipster/Presentation/Scene/UnvisitedClipList/ViewController/UnvisitedClipListViewController.swift
Labels: refactor, bugfix

#133 [Feat] ClipGridCell UI 구현
  Clipster/Clipster/Presentation/Scene/Common/Cell/ClipGirdCell.swift
  Clipster/Clipster/Presentation/Scene/Home/Subview/View/HomeView.swift
Labels: feature

#144 [Feat] ClipCell, FolderCell을 TableViewCell로 변경
  Clipster/Clipster/Presentation/Scene/Common/Cell/ClipCell.swift
  Clipster/Clipster/Presentation/Scene/Common/Cell/FolderCell.swift
  Clipster/Clipster/Presentation/Scene/Folder/Subview/View/FolderView.swift
  Clipster/Clipster/Presentation/Scene/Home/Subview/View/HomeView.swift
  Clipster/Clipster/Presentation/Scene/UnvisitedClipList/SubView/View/UnvisitedClipListView.swift
Labels: refactor

#139 [Feat] 홈 뷰, 방문하지 않은 클립 뷰 네비게이션 뷰 적용
  Clipster/Clipster/Presentation/Scene/Common/Button/BackButton.swift
  Clipster/Clipster/Presentation/Scene/Home/Subview/View/HomeView.swift
  Clipster/Clipster/Presentation/Scene/Home/ViewController/HomeViewController.swift
  Clipster/Clipster/Presentation/Scene/UnvisitedClipList/SubView/View/UnvisitedClipListView.swift
  Clipster/Clipster/Presentation/Scene/UnvisitedClipList/ViewController/UnvisitedClipListViewController.swift
  Clipster/Clipster/Presentation/Scene/UnvisitedClipList/ViewModel/UnvisitedClipListViewModel.swift
Labels: feature

#142 [Feat] 클립 편집화면 전환 구현
  Clipster/Clipster/Presentation/Scene/ClipDetail/Subview/Button/ClipDetailBackButton.swift
  Clipster/Clipster/Presentation/Scene/ClipDetail/Subview/Button/ClipDetailDeleteButton.swift
  Clipster/Clipster/Presentation/Scene/ClipDetail/Subview/Button/ClipDetailEditButton.swift
  Clipster/Clipster/Presentation/Scene/ClipDetail/ViewController/ClipDetailViewController.swift
Labels: feature

#147 [Feat] 조건에 따른 폴더 선택 버튼 비활성화 구현
  Clipster/Clipster/Presentation/Scene/Common/Button/SaveButton.swift
  Clipster/Clipster/Presentation/Scene/Common/Button/SelectButton.swift
  Clipster/Clipster/Presentation/Scene/EditFolder/ViewModel/EditFolderViewModel.swift
  Clipster/Clipster/Presentation/Scene/FolderSelector/Subview/View/FolderSelectorNavigationView.swift
  Clipster/Clipster/Presentation/Scene/FolderSelector/Subview/View/FolderSelectorView.swift
  Clipster/Clipster/Presentation/Scene/FolderSelector/ViewController/FolderSelectorViewController.swift
  Clipster/Clipster/Presentation/Scene/FolderSelector/ViewModel/FolderSelectorViewModel.swift
Labels: feature

#149 [Feat] 클립 상세 화면 디자인 변경사항 반영
  Clipster/Clipster/Presentation/Scene/ClipDetail/Subview/View/ClipDetailMemoView.swift
  Clipster/Clipster/Presentation/Scene/ClipDetail/Subview/View/ClipDetailRowView.swift
  Clipster/Clipster/Presentation/Scene/ClipDetail/Subview/View/ClipDetailView.swift
  Clipster/Clipster/Presentation/Scene/ClipDetail/ViewController/ClipDetailViewController.swift
  Clipster/Clipster/Presentation/Scene/Common/TextField/CommonTextField.swift
  Clipster/Clipster/Presentation/Scene/Common/View/MemoView.swift
  Clipster/Clipster/Presentation/Scene/Common/View/URLMetadataView.swift
  Clipster/Clipster/Presentation/Scene/Common/View/URLView.swift
  Clipster/Clipster/Presentation/Scene/EditFolder/Subview/View/EditFolderView.swift
Labels: feature

#156 [Refactor] TableHeaderView 구현
  Clipster/Clipster/Presentation/Scene/Common/Cell/TableHeaderView.swift
  Clipster/Clipster/Presentation/Scene/Home/Subview/Cell/CollectionHeaderView.swift
  Clipster/Clipster/Presentation/Scene/Home/Subview/View/HomeView.swift
Labels: refactor

#157 [Feat] FolderCell, FolderSelectorCell 통합
  Clipster/Clipster/Presentation/Scene/Common/Cell/FolderCell.swift
  Clipster/Clipster/Presentation/Scene/FolderSelector/Cell/FolderSelectorCell.swift
  Clipster/Clipster/Presentation/Scene/FolderSelector/Subview/View/FolderSelectorView.swift
  Clipster/Clipster/Presentation/Scene/FolderSelector/ViewController/FolderSelectorViewController.swift
Labels: refactor

#160 [Feat] 클립 상세 화면 데이터 바인딩
  Clipster/Clipster/Presentation/Model/ClipDisplay.swift
  Clipster/Clipster/Presentation/Scene/ClipDetail/Subview/View/ClipDetailView.swift
  Clipster/Clipster/Presentation/Scene/ClipDetail/ViewController/ClipDetailViewController.swift
  Clipster/Clipster/Presentation/Scene/ClipDetail/ViewModel/ClipDetailViewModel.swift
  Clipster/Clipster/Presentation/Scene/EditFolder/Subview/View/EditFolderView.swift
  Clipster/Clipster/Presentation/Util/Mapper/ClipDisplayMapper.swift
Labels: feature

#137 [Feat] Share Extension 구현
  Clipster/Clipster.xcodeproj/project.pbxproj
  Clipster/Clipster/App/DIContainer/DIContainer.swift
  Clipster/Clipster/App/Derived/Info.plist
  Clipster/Clipster/App/Source/SceneDelegate.swift
  Clipster/ShareExtension/Info.plist
  Clipster/ShareExtension/ShareExtension.entitlements
  Clipster/ShareExtension/ShareViewController.swift
Labels: feature

#164 [Refactor] 방문하지 않은 클립 뷰 테이블뷰로 변경
  Clipster/Clipster/Presentation/Scene/UnvisitedClipList/SubView/View/UnvisitedClipListView.swift
Labels: refactor

#168 [FEAT] PROVISIONING 갱신
  Clipster/Clipster.xcodeproj/project.pbxproj
Labels: chore

#169 [Feat]: EditClipView 네비게이션 공통 뷰 추가
  Clipster/Clipster/Presentation/Scene/EditClip/Subview/View/EditClipView.swift
  Clipster/Clipster/Presentation/Scene/EditClip/ViewController/EditClipViewController.swift
Labels: refactor

#172 [Feat] Asset 항목 추가
  Clipster/Clipster/Presentation/Resource/Color.xcassets/White/Contents.json
  Clipster/Clipster/Presentation/Resource/Color.xcassets/White/White800.colorset/Contents.json
  Clipster/Clipster/Presentation/Resource/Color.xcassets/White/White900.colorset/Contents.json
  Clipster/Clipster/Presentation/Resource/Icon.xcassets/FolderPlus.imageset/Contents.json
  Clipster/Clipster/Presentation/Resource/Icon.xcassets/FolderPlus.imageset/folder-plus.svg
  Clipster/Clipster/Presentation/Resource/Icon.xcassets/TrashWhite.imageset/Contents.json
  Clipster/Clipster/Presentation/Resource/Icon.xcassets/TrashWhite.imageset/trash-2.svg
Labels: chore

#175 [Refator] ShareExtension 최소 요구 iOS 버전 및 지원 기기 변경
  Clipster/Clipster.xcodeproj/project.pbxproj
Labels: chore

#178 홈화면에서 폴더 안보이는 버그 수정
  Clipster/Clipster/Presentation/Scene/Home/ViewModel/HomeViewModel.swift
Labels: fix

#186 FolderCell과 FolderSelectorCell 분리
  Clipster/Clipster/Presentation/Scene/FolderSelector/Subview/Cell/FolderSelectorCell.swift
  Clipster/Clipster/Presentation/Scene/FolderSelector/Subview/View/FolderSelectorView.swift
  Clipster/Clipster/Presentation/Scene/FolderSelector/ViewController/FolderSelectorViewController.swift
Labels: refactor

#189 EditClipView 저장/수정 버튼 로직 구현
  Clipster/Clipster/App/DIContainer/DIContainer.swift
  Clipster/Clipster/Domain/Protocol/UseCase/Clip/CreateClipUseCase.swift
  Clipster/Clipster/Domain/Protocol/UseCase/Clip/UpdateClipUseCase.swift
  Clipster/Clipster/Domain/UseCase/Clip/DefaultCreateClipUseCase.swift
  Clipster/Clipster/Domain/UseCase/Clip/DefaultUpdateClipUseCase.swift
  Clipster/Clipster/Presentation/Scene/EditClip/ViewController/EditClipViewController.swift
  Clipster/Clipster/Presentation/Scene/EditClip/ViewModel/EditClipViewModel.swift
Labels: feat, refactor

#188 홈 뷰 UI 피그마 동기화
  Clipster/Clipster/Presentation/Scene/Common/Cell/ClipGirdCell.swift
  Clipster/Clipster/Presentation/Scene/Common/Cell/TableHeaderView.swift
  Clipster/Clipster/Presentation/Scene/Home/Subview/Cell/CollectionHeaderView.swift
  Clipster/Clipster/Presentation/Scene/Home/Subview/View/HomeView.swift
Labels: refactor

#197 EmptyView 구현
  Clipster/Clipster/Presentation/Resource/Icon.xcassets/Empty.imageset/Contents.json
  Clipster/Clipster/Presentation/Resource/Icon.xcassets/Empty.imageset/empty.svg
  Clipster/Clipster/Presentation/Scene/Common/View/EmptyView.swift
Labels: feat

#199 폴더 추가 화면, 클립 상세 화면, 폴더 선택 화면 assets 적용
  Clipster/Clipster/Presentation/Scene/ClipDetail/Subview/View/ClipDetailView.swift
  Clipster/Clipster/Presentation/Scene/Common/View/FolderRowView.swift
  Clipster/Clipster/Presentation/Scene/EditFolder/Subview/View/EditFolderView.swift
  Clipster/Clipster/Presentation/Scene/FolderSelector/Subview/Cell/FolderSelectorCell.swift
  Clipster/Clipster/Presentation/Scene/FolderSelector/Subview/View/FolderSelectorNavigationView.swift
  Clipster/Clipster/Presentation/Scene/FolderSelector/Subview/View/FolderSelectorView.swift
  Clipster/Clipster/Presentation/Scene/FolderSelector/ViewController/FolderSelectorViewController.swift
Labels: feat

#201 홈 선택시 폴더 선택 화면 보이게 수정
  Clipster/Clipster/Presentation/Scene/EditFolder/ViewController/EditFolderViewController.swift
Labels: fix

#203 soft-deleted 항목을 fetch하지 않도록 수정
  Clipster/Clipster/Data/Persistence/DefaultFolderStorage.swift
Labels: fix

#204 FolderView UI/UX 상세 구현
  Clipster/Clipster/App/DIContainer/DIContainer.swift
  Clipster/Clipster/Presentation/Scene/Common/Button/AddButton.swift
  Clipster/Clipster/Presentation/Scene/Common/Button/BackButton.swift
  Clipster/Clipster/Presentation/Scene/Common/Cell/ClipCell.swift
  Clipster/Clipster/Presentation/Scene/Common/Cell/FolderCell.swift
  Clipster/Clipster/Presentation/Scene/Common/Cell/TableHeaderView.swift
  Clipster/Clipster/Presentation/Scene/Common/View/CommonNavigationView.swift
  Clipster/Clipster/Presentation/Scene/Common/View/EmptyView.swift
  Clipster/Clipster/Presentation/Scene/Folder/Subview/View/FolderView.swift
  Clipster/Clipster/Presentation/Scene/Folder/ViewController/FolderViewController.swift
  Clipster/Clipster/Presentation/Scene/Folder/ViewModel/FolderViewModel.swift
Labels: feat, fix

#209 홈 뷰 폴더 섹션 ListConfiguration으로 리팩토링
  Clipster/Clipster/Presentation/Scene/Common/Cell/FolderListCell.swift
  Clipster/Clipster/Presentation/Scene/Home/Subview/Cell/ClipGirdCell.swift
  Clipster/Clipster/Presentation/Scene/Home/Subview/View/HomeView.swift
  Clipster/Clipster/Presentation/Scene/Home/ViewController/HomeViewController.swift
  Clipster/Clipster/Presentation/Scene/Home/ViewModel/HomeViewModel.swift
Labels: refactor

#216 CoreData 비동기 동작으로 개선
  Clipster/Clipster/App/DIContainer/DIContainer.swift
  Clipster/Clipster/Data/Error/CoreDataError.swift
  Clipster/Clipster/Data/Persistence/CoreDataStack.swift
  Clipster/Clipster/Data/Persistence/DefaultClipStorage.swift
  Clipster/Clipster/Data/Persistence/DefaultFolderStorage.swift
  Clipster/Clipster/Data/Protocol/Persistence/ClipStorage.swift
  Clipster/Clipster/Data/Protocol/Persistence/FolderStorage.swift
  Clipster/Clipster/Data/Repository/Clip/DefaultClipRepository.swift
  Clipster/Clipster/Data/Repository/Folder/DefaultFolderRepository.swift
  Clipster/Clipster/Domain/Protocol/Repository/Clip/ClipRepository.swift
  Clipster/Clipster/Domain/Protocol/Repository/Folder/FolderRepository.swift
  Clipster/Clipster/Domain/UseCase/Clip/DefaultCreateClipUseCase.swift
  Clipster/Clipster/Domain/UseCase/Clip/DefaultDeleteClipUseCase.swift
  Clipster/Clipster/Domain/UseCase/Clip/DefaultFetchClipUseCase.swift
  Clipster/Clipster/Domain/UseCase/Clip/DefaultFetchUnvisitedClipUseCase.swift
  Clipster/Clipster/Domain/UseCase/Clip/DefaultUpdateClipUseCase.swift
  Clipster/Clipster/Domain/UseCase/Folder/DefaultCreateFolderUseCase.swift
  Clipster/Clipster/Domain/UseCase/Folder/DefaultDeleteFolderUseCase.swift
  Clipster/Clipster/Domain/UseCase/Folder/DefaultFetchFolderUseCase.swift
  Clipster/Clipster/Domain/UseCase/Folder/DefaultFetchTopLevelFoldersUseCase.swift
  Clipster/Clipster/Domain/UseCase/Folder/DefaultUpdateFolderUseCase.swift
Labels: refactor

#213 버튼 터치 영역 수정
  Clipster/Clipster/Presentation/Scene/ClipDetail/Subview/View/ClipDetailView.swift
  Clipster/Clipster/Presentation/Scene/Common/Button/AddButton.swift
  Clipster/Clipster/Presentation/Scene/Common/Button/BackButton.swift
  Clipster/Clipster/Presentation/Scene/Common/Button/DeleteButton.swift
  Clipster/Clipster/Presentation/Scene/Common/Button/EditButton.swift
  Clipster/Clipster/Presentation/Scene/Common/Button/InfoButton.swift
  Clipster/Clipster/Presentation/Scene/Common/Button/SaveButton.swift
  Clipster/Clipster/Presentation/Scene/Common/Button/SelectButton.swift
  Clipster/Clipster/Presentation/Scene/Common/View/CommonNavigationView.swift
  Clipster/Clipster/Presentation/Scene/EditClip/Subview/View/EditClipView.swift
  Clipster/Clipster/Presentation/Scene/EditFolder/Subview/View/EditFolderView.swift
  Clipster/Clipster/Presentation/Scene/Folder/Subview/View/FolderView.swift
  Clipster/Clipster/Presentation/Scene/FolderSelector/Subview/View/FolderSelectorView.swift
  Clipster/Clipster/Presentation/Scene/Home/Subview/View/HomeView.swift
Labels: fix

#219 방문하지 않은 클립 뷰 리팩토링 및 Alert 추가
  Clipster/Clipster/Presentation/Scene/ClipDetail/ViewController/ClipDetailViewController.swift
  Clipster/Clipster/Presentation/Scene/Common/Cell/ClipListCell.swift
  Clipster/Clipster/Presentation/Scene/Folder/ViewController/FolderViewController.swift
  Clipster/Clipster/Presentation/Scene/Home/Subview/View/HomeView.swift
  Clipster/Clipster/Presentation/Scene/UnvisitedClipList/SubView/View/UnvisitedClipListView.swift
  Clipster/Clipster/Presentation/Scene/UnvisitedClipList/ViewController/UnvisitedClipListViewController.swift
  Clipster/Clipster/Presentation/Util/Extension/ViewController+Extension.swift
Labels: refactor

#218 EditClipView UI 프로토타입 동기화
  Clipster/Clipster/Presentation/Scene/Common/StackView/URLMetadataStackView.swift
  Clipster/Clipster/Presentation/Scene/EditClip/Subview/StackView/URLValidationStackView.swift
  Clipster/Clipster/Presentation/Scene/EditClip/Subview/View/EditClipView.swift
  Clipster/Clipster/Presentation/Scene/EditClip/ViewController/EditClipViewController.swift
  Clipster/Clipster/Presentation/Scene/EditClip/ViewModel/EditClipViewModel.swift
Labels: feat, refactor

#222 홈화면 EmptyView 적용 및 Alert
  Clipster/Clipster/Presentation/Resource/Icon.xcassets/Empty.imageset/empty.svg
  Clipster/Clipster/Presentation/Scene/Home/Subview/View/HomeView.swift
  Clipster/Clipster/Presentation/Scene/Home/ViewController/HomeViewController.swift
  Clipster/Clipster/Presentation/Scene/UnvisitedClipList/ViewController/UnvisitedClipListViewController.swift
Labels: feat

#247 내비게이션 타이틀 길이 제한
  Clipster/Clipster/Presentation/Scene/Common/View/CommonNavigationView.swift
  Clipster/Clipster/Presentation/Scene/Folder/Subview/View/FolderView.swift
Labels: fix

#248 폴더 추가/편집 화면에서 빈화면 클릭 시 키보드 숨김
  Clipster/Clipster/Presentation/Scene/EditFolder/ViewController/EditFolderViewController.swift
Labels: feat

#257 폴더, 클립 정렬
  Clipster/Clipster/Domain/UseCase/Clip/DefaultFetchUnvisitedClipUseCase.swift
  Clipster/Clipster/Domain/UseCase/Folder/DefaultFetchFolderUseCase.swift
  Clipster/Clipster/Domain/UseCase/Folder/DefaultFetchTopLevelFoldersUseCase.swift
Labels: fix

#255 폴더 섹션만 있을경우 문제 해결
  Clipster/Clipster/Presentation/Scene/Home/Subview/View/HomeView.swift
Labels: fix

#259 헤더뷰 재사용으로 인한 중복 바인딩 해결
  Clipster/Clipster/Presentation/Scene/Home/Subview/Cell/CollectionHeaderView.swift
  Clipster/Clipster/Presentation/Scene/Home/Subview/View/HomeView.swift
Labels: fix

#253 EditClipView ScrollView 적용
  Clipster/Clipster/Presentation/Scene/EditClip/Subview/View/EditClipView.swift
Labels: feat

#249 indent 5칸 -> 4칸으로 수정
  Clipster/Clipster/Domain/Protocol/UseCase/Clip/FetchUnvisitedClipsUseCase.swift
  Clipster/Clipster/Domain/UseCase/Clip/DefaultDeleteClipUseCase.swift
  Clipster/Clipster/Domain/UseCase/Clip/DefaultFetchClipUseCase.swift
  Clipster/Clipster/Domain/UseCase/Clip/DefaultFetchUnvisitedClipsUseCase.swift
Labels: refactor

#263 폴더 뷰에서 클립 추가 시 최근 수정된 폴더로 보이는 문제 해결
  Clipster/Clipster/Presentation/Scene/EditClip/ViewController/EditClipViewController.swift
  Clipster/Clipster/Presentation/Scene/Folder/ViewController/FolderViewController.swift
  Clipster/Clipster/Presentation/Scene/Folder/ViewModel/FolderViewModel.swift
Labels: fix

#272 InteractivePopGesture 활성화
  Clipster/Clipster/Presentation/Scene/ClipDetail/ViewController/ClipDetailViewController.swift
  Clipster/Clipster/Presentation/Scene/EditClip/ViewController/EditClipViewController.swift
  Clipster/Clipster/Presentation/Scene/EditFolder/ViewController/EditFolderViewController.swift
  Clipster/Clipster/Presentation/Scene/Folder/ViewController/FolderViewController.swift
  Clipster/Clipster/Presentation/Scene/UnvisitedClipList/ViewController/UnvisitedClipListViewController.swift
Labels: feat

#274 클립 추가/편집 화면에서 폴더 선택 시 홈이 선택되는 버그 수정
  Clipster/Clipster/Presentation/Scene/EditFolder/ViewController/EditFolderViewController.swift
  Clipster/Clipster/Presentation/Scene/EditFolder/ViewModel/EditFolderViewModel.swift
  Clipster/Clipster/Presentation/Scene/FolderSelector/ViewController/FolderSelectorViewController.swift
  Clipster/Clipster/Presentation/Scene/FolderSelector/ViewModel/FolderSelectorViewModel.swift
Labels: fix

#268 폴더 화면 단일 섹션일 때 여백 조정
  Clipster/Clipster/Presentation/Scene/Folder/Subview/View/FolderView.swift
Labels: fix

#276 클립 추가 화면에서 폴더 label trailing 제약 조건 추가
  Clipster/Clipster/Presentation/Scene/EditClip/Subview/View/EditClipView.swift
Labels: fix

#279 홈 폴더 섹션만 있을경우 위쪽 여백 다름 해결 및 기타 수정
  Clipster/Clipster/Presentation/Scene/Home/Subview/Cell/ClipGirdCell.swift
  Clipster/Clipster/Presentation/Scene/Home/Subview/View/HomeView.swift
Labels: fix

#280 앱 메타데이터 입력 및 프로비저닝 파일 갱신
  Clipster/Clipster.xcodeproj/project.pbxproj
  Clipster/Clipster/App/ClipsterDebug.entitlements
  Clipster/Clipster/App/ClipsterRelease.entitlements
  Clipster/Clipster/App/Derived/Info.plist
  Clipster/Clipster/Data/Persistence/CoreDataStack.swift
  Clipster/Clipster/Domain/UseCase/URLValidation/DefaultCheckVaildityUseCase.swift
  Clipster/ShareExtension/Info.plist
  Clipster/ShareExtension/ShareExtensionDebug.entitlements
  Clipster/ShareExtension/ShareExtensionRelease.entitlements
  Clipster/ShareExtension/ShareViewController.swift
Labels: chore

#286 InteractivePopGesture 연달아 pop 안됨 해결
  Clipster/Clipster/Presentation/Scene/ClipDetail/ViewController/ClipDetailViewController.swift
  Clipster/Clipster/Presentation/Scene/EditClip/ViewController/EditClipViewController.swift
  Clipster/Clipster/Presentation/Scene/EditFolder/ViewController/EditFolderViewController.swift
  Clipster/Clipster/Presentation/Scene/Folder/ViewController/FolderViewController.swift
  Clipster/Clipster/Presentation/Scene/UnvisitedClipList/ViewController/UnvisitedClipListViewController.swift
Labels: fix

#290 fix: animatingDifferences 변경
  Clipster/Clipster/Presentation/Scene/Folder/Subview/View/FolderView.swift
  Clipster/Clipster/Presentation/Scene/Home/Subview/View/HomeView.swift
  Clipster/Clipster/Presentation/Scene/UnvisitedClipList/SubView/View/UnvisitedClipListView.swift
Labels: fix

#291 URL Scheme 구분하여 Share Extension 이슈 해결
  Clipster/Clipster/App/Derived/Info.plist
  Clipster/Clipster/App/Source/SceneDelegate.swift
  Clipster/ShareExtension/ShareViewController.swift
Labels: fix

#292 fix: 텍스트 필드 피그마 디자인 반영
  Clipster/Clipster/Presentation/Scene/ClipDetail/Subview/View/ClipDetailView.swift
  Clipster/Clipster/Presentation/Scene/Common/TextField/CommonTextField.swift
  Clipster/Clipster/Presentation/Scene/EditClip/Subview/View/EditClipView.swift
Labels: fix

#296 클립 편집 URL 입력 키보드 타입 변경 및 소문자 적용
  Clipster/Clipster/Presentation/Scene/EditClip/Subview/View/EditClipView.swift
Labels: fix

#297 URL 적합성 여부 관련 이미지 안 사라지는 문제 해결
  Clipster/Clipster/Presentation/Scene/EditClip/ViewController/EditClipViewController.swift
Labels: fix

#299 메모 텍스트뷰 높이 수정
  Clipster/Clipster/Presentation/Scene/Common/View/MemoView.swift
Labels: fix

#308 내비게이션 타이틀 정렬 문제 수정
  Clipster/Clipster/Presentation/Scene/Common/View/CommonNavigationView.swift
Labels: fix

#302 폴더 제목 글자수 제한 label 가운데 정렬
  Clipster/Clipster/Presentation/Scene/EditFolder/Subview/View/EditFolderView.swift
Labels: fix

#309 색상 적용 안된 부분 수정
  Clipster/Clipster/App/Source/SceneDelegate.swift
  Clipster/Clipster/Presentation/Scene/ClipDetail/Subview/View/ClipDetailView.swift
  Clipster/Clipster/Presentation/Scene/Common/Cell/FolderListCell.swift
  Clipster/Clipster/Presentation/Scene/EditClip/Subview/View/EditClipView.swift
  Clipster/Clipster/Presentation/Scene/Home/Subview/Cell/ClipGirdCell.swift
Labels: fix

#310 저장 버튼 활성화 여부 수정
  Clipster/Clipster/Presentation/Scene/EditClip/ViewController/EditClipViewController.swift
Labels: fix

#311 FolderListCell 오토레이아웃 경고 해결
  Clipster/Clipster/Presentation/Scene/Common/Cell/FolderListCell.swift
Labels: fix

#313 ClipCell 배경색상 설정
  Clipster/Clipster/Presentation/Scene/Common/Cell/ClipCell.swift
  Clipster/Clipster/Presentation/Scene/Common/Cell/ClipListCell.swift
  Clipster/Clipster/Presentation/Scene/Home/Subview/Cell/ClipGirdCell.swift
Labels: fix

#319 배지 디자인 수정
  Clipster/Clipster/Presentation/Scene/Common/Cell/ClipCell.swift
  Clipster/Clipster/Presentation/Scene/Common/Cell/ClipListCell.swift
  Clipster/Clipster/Presentation/Scene/Home/Subview/Cell/ClipGirdCell.swift
Labels: fix

#315 폴더 편집, 클립 편집, 클립 상세 화면 제약조건 수정
  Clipster/Clipster/Presentation/Scene/ClipDetail/Subview/View/ClipDetailView.swift
  Clipster/Clipster/Presentation/Scene/Common/View/CommonNavigationView.swift
  Clipster/Clipster/Presentation/Scene/Common/View/MemoView.swift
  Clipster/Clipster/Presentation/Scene/Common/View/ThumbnailView.swift
  Clipster/Clipster/Presentation/Scene/Common/View/URLView.swift
  Clipster/Clipster/Presentation/Scene/EditClip/Subview/View/EditClipView.swift
  Clipster/Clipster/Presentation/Scene/EditFolder/Subview/View/EditFolderView.swift
  Clipster/Clipster/Presentation/Util/Mapper/FolderDisplayMapper.swift
Labels: fix

#321 폴더 선택 모달 높이 비율 수정 및 클립 상세 화면 타이틀 수정
  Clipster/Clipster/Presentation/Scene/ClipDetail/Subview/View/ClipDetailView.swift
  Clipster/Clipster/Presentation/Scene/EditClip/ViewController/EditClipViewController.swift
  Clipster/Clipster/Presentation/Scene/EditFolder/ViewController/EditFolderViewController.swift
Labels: fix

#328 썸네일이 없어도 오류로 처리하지 않도록 수정
  Clipster/Clipster/Data/Util/Mapper/DomainMapper.swift
Labels: fix

#323 메모 터치 안되는 이슈 수정
  Clipster/Clipster/Presentation/Scene/ClipDetail/Subview/View/ClipDetailView.swift
  Clipster/Clipster/Presentation/Scene/Common/View/MemoView.swift
Labels: fix

#336 폴더 선택 뷰 한번만 클릭되는 문제 수정
  Clipster/Clipster/Presentation/Scene/EditClip/ViewController/EditClipViewController.swift
Labels: fix

#334 홈, 방문하지 않은 클립 화면 push 한번만 일어나도록 수정
  Clipster/Clipster/Presentation/Scene/Home/ViewController/HomeViewController.swift
  Clipster/Clipster/Presentation/Scene/UnvisitedClipList/ViewController/UnvisitedClipListViewController.swift
Labels: fix

#352 Package Dependency 변경
  Clipster/Clipster.xcodeproj/project.pbxproj
  Clipster/Clipster.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: chore

#361 URL 수정 시 Unread 상태로 변경
  Clipster/Clipster/Presentation/Scene/EditClip/ViewModel/EditClipViewModel.swift
Labels: feat

#362 클립 추가 / 상세 화면 공통 컴포넌트 수정
  Clipster/Clipster/Presentation/Scene/ClipDetail/Subview/View/ClipDetailView.swift
  Clipster/Clipster/Presentation/Scene/ClipDetail/ViewController/ClipDetailViewController.swift
  Clipster/Clipster/Presentation/Scene/Common/StackView/URLMetadataStackView.swift
  Clipster/Clipster/Presentation/Scene/Common/TextField/CommonTextField.swift
  Clipster/Clipster/Presentation/Scene/Common/View/SelectedFolderView.swift
  Clipster/Clipster/Presentation/Scene/Common/View/ThumbnailView.swift
  Clipster/Clipster/Presentation/Scene/Common/View/URLView.swift
  Clipster/Clipster/Presentation/Scene/EditClip/Subview/View/EditClipView.swift
  Clipster/Clipster/Presentation/Scene/EditClip/ViewController/EditClipViewController.swift
Labels: fix

#365 URLMetadata/URLValidation 통합
  Clipster/Clipster/App/DIContainer/DIContainer.swift
  Clipster/Clipster/Data/Repository/URL/DefaultURLRepository.swift
  Clipster/Clipster/Data/Repository/URLValidation/DefaultURLValidationRepository.swift
  Clipster/Clipster/Domain/Model/ParsedURLMetadata.swift
  Clipster/Clipster/Domain/Protocol/Repository/URL/URLRepository.swift
  Clipster/Clipster/Domain/Protocol/Repository/URLMetadata/URLMetadataRepository.swift
  Clipster/Clipster/Domain/Protocol/Repository/URLValidation/URLValidationRepository.swift
  Clipster/Clipster/Domain/Protocol/UseCase/URL/ParseURLUseCase.swift
  Clipster/Clipster/Domain/Protocol/UseCase/URLMetadata/ParseURLMetadataUseCase.swift
  Clipster/Clipster/Domain/Protocol/UseCase/URLValidation/CheckURLValidityUseCase.swift
  Clipster/Clipster/Domain/UseCase/URL/DefaultParseURLUseCase.swift
  Clipster/Clipster/Domain/UseCase/URLMetadata/DefaultParseURLMetadataUseCase.swift
  Clipster/Clipster/Domain/UseCase/URLValidation/DefaultCheckVaildityUseCase.swift
  Clipster/Clipster/Presentation/Scene/EditClip/ViewModel/EditClipViewModel.swift
Labels: refactor

#375 홈화면 EmtpyAddButton 추가
  Clipster/Clipster/Presentation/Resource/Icon.xcassets/AddButtonBlue.imageset/AddButtonBlue.png
  Clipster/Clipster/Presentation/Resource/Icon.xcassets/AddButtonBlue.imageset/Contents.json
  Clipster/Clipster/Presentation/Scene/Common/View/EmptyView.swift
  Clipster/Clipster/Presentation/Scene/Home/Subview/View/HomeView.swift
Labels: feat

#367 TextField 수정 사항 반영
  Clipster/Clipster/Presentation/Resource/Icon.xcassets/XGray.imageset/Contents.json
  Clipster/Clipster/Presentation/Resource/Icon.xcassets/XGray.imageset/XGray.svg
  Clipster/Clipster/Presentation/Scene/ClipDetail/Subview/View/ClipDetailView.swift
  Clipster/Clipster/Presentation/Scene/Common/TextField/CommonTextField.swift
  Clipster/Clipster/Presentation/Scene/Common/View/SelectedFolderView.swift
  Clipster/Clipster/Presentation/Scene/EditClip/Subview/View/EditClipView.swift
  Clipster/Clipster/Presentation/Scene/EditClip/ViewController/EditClipViewController.swift
  Clipster/Clipster/Presentation/Scene/EditFolder/Subview/View/EditFolderView.swift
  Clipster/Clipster/Presentation/Scene/EditFolder/ViewController/EditFolderViewController.swift
  Clipster/Clipster/Presentation/Scene/EditFolder/ViewModel/EditFolderViewModel.swift
Labels: fix

#371 내비게이션 바 높이 디자인에 맞게 수정
  Clipster/Clipster/Presentation/Scene/Common/View/CommonNavigationView.swift
  Clipster/Clipster/Presentation/Scene/FolderSelector/Subview/View/FolderSelectorView.swift
Labels: fix

#377 방문하지 않은 클립 화면 ReactorKit 적용
  Clipster/Clipster/App/DIContainer/DIContainer.swift
  Clipster/Clipster/Presentation/Scene/Home/ViewController/HomeViewController.swift
  Clipster/Clipster/Presentation/Scene/UnvisitedClipList/Reactor/UnvisitedClipListReactor.swift
  Clipster/Clipster/Presentation/Scene/UnvisitedClipList/SubView/View/UnvisitedClipListView.swift
  Clipster/Clipster/Presentation/Scene/UnvisitedClipList/ViewController/UnvisitedClipListViewController.swift
  Clipster/Clipster/Presentation/Scene/UnvisitedClipList/ViewModel/UnvisitedClipListViewModel.swift
Labels: refactor

#384 FolderSelectorViewModel 리팩토링
  Clipster/Clipster/App/DIContainer/DIContainer.swift
  Clipster/Clipster/Domain/Protocol/UseCase/Folder/CanSelectFolderUseCase.swift
  Clipster/Clipster/Domain/Protocol/UseCase/Folder/FilterSubfoldersUseCase.swift
  Clipster/Clipster/Domain/Protocol/UseCase/Folder/FindFolderPathUseCase.swift
  Clipster/Clipster/Domain/UseCase/Folder/DefaultCanSelectFolderUseCase.swift
  Clipster/Clipster/Domain/UseCase/Folder/DefaultFilterSubfoldersUseCase.swift
  Clipster/Clipster/Domain/UseCase/Folder/DefaultFindFolderPathUseCase.swift
  Clipster/Clipster/Presentation/Scene/EditClip/ViewController/EditClipViewController.swift
  Clipster/Clipster/Presentation/Scene/EditFolder/ViewController/EditFolderViewController.swift
  Clipster/Clipster/Presentation/Scene/FolderSelector/Reactor/FolderSelectorReactor.swift
  Clipster/Clipster/Presentation/Scene/FolderSelector/ViewController/FolderSelectorViewController.swift
  Clipster/Clipster/Presentation/Scene/FolderSelector/ViewModel/FolderSelectorViewModel.swift
Labels: refactor

#380 홈화면 섹션별 높이 같도록 수정
  Clipster/Clipster/Presentation/Scene/Home/Subview/View/HomeView.swift
Labels: fix

#381 URLSession -> WebKit 마이그레이션
  Clipster/Clipster/App/DIContainer/DIContainer.swift
  Clipster/Clipster/Data/DTO/ParsedURLMetadataDTO.swift
  Clipster/Clipster/Data/Repository/URL/DefaultURLRepository.swift
  Clipster/Clipster/Domain/Model/ParsedURLMetadata.swift
  Clipster/Clipster/Domain/Protocol/Repository/URL/URLRepository.swift
  Clipster/Clipster/Domain/Protocol/UseCase/URL/ParseURLUseCase.swift
  Clipster/Clipster/Domain/UseCase/URL/DefaultParseURLUseCase.swift
  Clipster/Clipster/Presentation/Model/URLMetadataDisplay.swift
  Clipster/Clipster/Presentation/Scene/Common/StackView/URLMetadataStackView.swift
  Clipster/Clipster/Presentation/Scene/EditClip/ViewModel/EditClipViewModel.swift
  Clipster/Clipster/Presentation/Util/Mapper/ClipDisplayMapper.swift
Labels: feat, refactor, fix

#382 EditClipViewModel Reactor 마이그레이션
  Clipster/Clipster/App/DIContainer/DIContainer.swift
  Clipster/Clipster/App/Source/SceneDelegate.swift
  Clipster/Clipster/Presentation/Scene/ClipDetail/ViewController/ClipDetailViewController.swift
  Clipster/Clipster/Presentation/Scene/EditClip/Reactor/EditClipReactor.swift
  Clipster/Clipster/Presentation/Scene/EditClip/Subview/View/EditClipView.swift
  Clipster/Clipster/Presentation/Scene/EditClip/ViewController/EditClipViewController.swift
  Clipster/Clipster/Presentation/Scene/EditClip/ViewModel/ViewModel.swift
  Clipster/Clipster/Presentation/Scene/Folder/ViewController/FolderViewController.swift
  Clipster/Clipster/Presentation/Scene/Home/ViewController/HomeViewController.swift
  Clipster/Clipster/Presentation/Scene/UnvisitedClipList/ViewController/UnvisitedClipListViewController.swift
Labels: feat, refactor

#389 EditClip updateAt 조건 수정
  Clipster/Clipster/Presentation/Scene/EditClip/Reactor/EditClipReactor.swift
Labels: fix

#405 URLMetadataEntity에 screenshotData 속성 추가
  Clipster/Clipster/Data/Model/Clipster.xcdatamodeld/.xccurrentversion
  Clipster/Clipster/Data/Model/Clipster.xcdatamodeld/Clipster2.xcdatamodel/contents
  Clipster/Clipster/Data/Model/URLMetadataEntity.swift
  Clipster/Clipster/Data/Persistence/CoreDataStack.swift
  Clipster/Clipster/Data/Persistence/DefaultClipStorage.swift
  Clipster/Clipster/Data/Util/Mapper/DomainMapper.swift
  Clipster/Clipster/Domain/Model/URLMetadata.swift
  Clipster/Clipster/Presentation/Scene/EditClip/Reactor/EditClipReactor.swift
Labels: feat

#400 클립 편집 화면 저장 버튼 활성화 관련 수정
  Clipster/Clipster/Presentation/Scene/EditClip/ViewController/EditClipViewController.swift
Labels: fix

#402 폴더 편집 시 텍스트 필드 비어있는 이슈 해결
  Clipster/Clipster/Presentation/Scene/ClipDetail/ViewController/ClipDetailViewController.swift
  Clipster/Clipster/Presentation/Scene/EditFolder/ViewController/EditFolderViewController.swift
Labels: fix

#399 Coordinator 적용
  Clipster/Clipster/App/Coordinator/App/AppCoordinator.swift
  Clipster/Clipster/App/Coordinator/Protocol/Coordinator.swift
  Clipster/Clipster/App/Source/SceneDelegate.swift
  Clipster/Clipster/Presentation/Coordinator/Home/HomeCoordinator.swift
  Clipster/Clipster/Presentation/Scene/ClipDetail/ViewController/ClipDetailViewController.swift
  Clipster/Clipster/Presentation/Scene/EditClip/ViewController/EditClipViewController.swift
  Clipster/Clipster/Presentation/Scene/EditFolder/ViewController/EditFolderViewController.swift
  Clipster/Clipster/Presentation/Scene/Folder/ViewController/FolderViewController.swift
  Clipster/Clipster/Presentation/Scene/FolderSelector/ViewController/FolderSelectorViewController.swift
  Clipster/Clipster/Presentation/Scene/Home/ViewController/HomeViewController.swift
  Clipster/Clipster/Presentation/Scene/UnvisitedClipList/ViewController/UnvisitedClipListViewController.swift
Labels: refactor

#410 스크린샷 이미지 적용
  Clipster/Clipster/Presentation/Scene/ClipDetail/Subview/View/ClipDetailView.swift
  Clipster/Clipster/Presentation/Scene/Common/Cell/ClipListCell.swift
  Clipster/Clipster/Presentation/Scene/Common/StackView/URLMetadataStackView.swift
  Clipster/Clipster/Presentation/Scene/EditClip/ViewController/EditClipViewController.swift
  Clipster/Clipster/Presentation/Scene/Home/Subview/Cell/ClipGirdCell.swift
  Clipster/Clipster/Presentation/Util/Mapper/ClipDisplayMapper.swift
Labels: refactor

#418 클립 편집화면 진입 시 유효성 검사
  Clipster/Clipster/Presentation/Scene/EditClip/ViewController/EditClipViewController.swift
Labels: fix

#421 클립 추가 시 first responder 적용
  Clipster/Clipster/Presentation/Scene/EditClip/ViewController/EditClipViewController.swift
Labels: fix

#462 UIViewController Extension 파일 네이밍 수정
  Clipster/Clipster/Presentation/Util/Extension/UIViewController+Extension.swift
Labels: chore

#468 CanSaveFolderUseCase 테스트 코드 추가
  Clipster/ClipsterTests/Domain/UseCase/Folder/CanSaveFolderUseCaseTests.swift
Labels: test

#470 URL Prefix 예외처리
  Clipster/Clipster/Domain/UseCase/URL/DefaultParseURLUseCase.swift
Labels: fix

#475 jpeg 압축 적용
  Clipster/Clipster/Data/Repository/URL/DefaultURLRepository.swift
Labels: fix

#486 FilterSubfoldersUseCase 테스트 코드 추가
  Clipster/ClipsterTests/Domain/UseCase/Folder/FilterSubfoldersUseCaseTests.swift
  Clipster/ClipsterTests/Domain/UseCase/UseCaseTests.swift
Labels: test

#487 FindFolderPathUseCase 테스트 코드 추가
  Clipster/ClipsterTests/Domain/UseCase/Folder/FindFolderPathUseCaseTests.swift
Labels: test

#488 SanitizeFolderTitleUseCase 테스트 코드 추가
  Clipster/ClipsterTests/Domain/UseCase/Folder/SanitizeFolderTitleUseCaseTests.swift
Labels: test

#476 HomeReactor 좀 더 선언형으로 리팩토링
  Clipster/Clipster/App/DIContainer/DIContainer.swift
  Clipster/Clipster/Domain/Protocol/UseCase/Clip/VisitClipUseCase.swift
  Clipster/Clipster/Domain/UseCase/Clip/DefaultVisitClipUseCase.swift
  Clipster/Clipster/Presentation/Scene/Home/Reactor/HomeReactor.swift
  Clipster/Clipster/Presentation/Scene/Home/ViewController/HomeViewController.swift
Labels: refactor

#503 URLMetadata를 Clip으로 통합
  Clipster/Clipster/Data/Model/Network/URLMetadataDTO.swift
  Clipster/Clipster/Data/Persistence/DefaultClipStorage.swift
  Clipster/Clipster/Data/Repository/URL/DefaultURLRepository.swift
  Clipster/Clipster/Data/Util/Mapper/DomainMapper.swift
  Clipster/Clipster/Domain/Model/Clip.swift
  Clipster/Clipster/Domain/Model/ParsedURLMetadata.swift
  Clipster/Clipster/Domain/Model/URLMetadata.swift
  Clipster/Clipster/Domain/Protocol/Repository/URL/URLRepository.swift
  Clipster/Clipster/Domain/Protocol/UseCase/URL/ParseURLUseCase.swift
  Clipster/Clipster/Domain/UseCase/Clip/DefaultDeleteClipUseCase.swift
  Clipster/Clipster/Domain/UseCase/Clip/DefaultVisitClipUseCase.swift
  Clipster/Clipster/Domain/UseCase/URL/DefaultParseURLUseCase.swift
  Clipster/Clipster/Presentation/Scene/EditClip/Reactor/EditClipReactor.swift
  Clipster/Clipster/Presentation/Scene/Folder/Reactor/FolderReactor.swift
  Clipster/Clipster/Presentation/Scene/Home/Reactor/HomeReactor.swift
  Clipster/Clipster/Presentation/Scene/UnvisitedClipList/Reactor/UnvisitedClipListReactor.swift
  Clipster/Clipster/Presentation/Util/Mapper/ClipDisplayMapper.swift
Labels: refactor

#477 정렬 로직 구현
  Clipster/Clipster/App/DIContainer/DIContainer.swift
  Clipster/Clipster/Domain/Model/Entity/Clip.swift
  Clipster/Clipster/Domain/Model/Entity/Folder.swift
  Clipster/Clipster/Domain/Model/Entity/URLMetadata.swift
  Clipster/Clipster/Domain/Model/VO/ClipSortOption.swift
  Clipster/Clipster/Domain/Model/VO/FolderSortOption.swift
  Clipster/Clipster/Domain/Model/VO/SortDirection.swift
  Clipster/Clipster/Domain/Protocol/UseCase/Clip/SortClipsUseCase.swift
  Clipster/Clipster/Domain/Protocol/UseCase/Folder/SortFoldersUseCase.swift
  Clipster/Clipster/Domain/UseCase/Clip/DefaultSortClipsUseCase.swift
  Clipster/Clipster/Domain/UseCase/Folder/DefaultSortFoldersUseCase.swift
  Clipster/Clipster/Domain/Util/Helper/SortHelper.swift
Labels: feat

#507 UnvisitedClipListReactor 좀 더 선언형으로 리팩토링
  Clipster/Clipster/App/DIContainer/DIContainer.swift
  Clipster/Clipster/Presentation/Scene/Home/Reactor/HomeReactor.swift
  Clipster/Clipster/Presentation/Scene/Home/ViewController/HomeViewController.swift
  Clipster/Clipster/Presentation/Scene/UnvisitedClipList/Reactor/UnvisitedClipListReactor.swift
  Clipster/Clipster/Presentation/Scene/UnvisitedClipList/ViewController/UnvisitedClipListViewController.swift
Labels: refactor

#505 애플 로그인을 통해 애플 JWT 받아오기
  Clipster/Clipster/App/ClipsterDebug.entitlements
  Clipster/Clipster/App/ClipsterRelease.entitlements
  Clipster/Clipster/App/DIContainer/DIContainer.swift
  Clipster/Clipster/Data/Network/Auth/AppleLoginService.swift
  Clipster/Clipster/Domain/Error/LoginError.swift
  Clipster/Clipster/Domain/Protocol/Service/Auth/SocialLoginService.swift
  Clipster/Clipster/Domain/Protocol/UseCase/Auth/LoginUseCase.swift
  Clipster/Clipster/Domain/UseCase/Auth/DefaultLoginUseCase.swift
  Clipster/Clipster/Domain/VO/LoginType.swift
Labels: feat

#510 FolderReactor 리팩터링
  Clipster/Clipster/App/DIContainer/DIContainer.swift
  Clipster/Clipster/Presentation/Scene/Folder/Reactor/FolderReactor.swift
Labels: refactor

#512 FolderView UI 개선
  Clipster/Clipster/Presentation/Scene/ClipDetail/ViewController/ClipDetailViewController.swift
  Clipster/Clipster/Presentation/Scene/EditFolder/ViewController/EditFolderViewController.swift
  Clipster/Clipster/Presentation/Scene/Folder/Subview/View/FolderView.swift
  Clipster/Clipster/Presentation/Scene/Folder/ViewController/FolderViewController.swift
  Clipster/Clipster/Presentation/Scene/Home/ViewController/HomeViewController.swift
  Clipster/Clipster/Presentation/Scene/UnvisitedClipList/ViewController/UnvisitedClipListViewController.swift
  Clipster/Clipster/Presentation/Util/Extension/UIViewController+Extension.swift
Labels: feat, refactor

#513 Description UI 적용
  Clipster/Clipster/Data/Util/Mapper/DomainMapper.swift
  Clipster/Clipster/Domain/Model/Entity/Clip.swift
  Clipster/Clipster/Domain/UseCase/Clip/DefaultDeleteClipUseCase.swift
  Clipster/Clipster/Domain/UseCase/Clip/DefaultVisitClipUseCase.swift
  Clipster/Clipster/Presentation/Model/URLMetadataDisplay.swift
  Clipster/Clipster/Presentation/Scene/Common/StackView/URLMetadataStackView.swift
  Clipster/Clipster/Presentation/Scene/EditClip/Reactor/EditClipReactor.swift
  Clipster/Clipster/Presentation/Util/Mapper/ClipDisplayMapper.swift
Labels: feat, refactor

#517 Subtitle 관련 스키마 수정
  Clipster/Clipster/Data/Model/Persistence/Clipster.xcdatamodeld/.xccurrentversion
  Clipster/Clipster/Data/Model/Persistence/Clipster.xcdatamodeld/Clipster3.xcdatamodel/contents
  Clipster/Clipster/Data/Model/Persistence/URLMetadataEntity.swift
  Clipster/Clipster/Data/Persistence/DefaultClipStorage.swift
  Clipster/Clipster/Data/Util/Mapper/DomainMapper.swift
  Clipster/Clipster/Domain/Model/Entity/Clip.swift
  Clipster/Clipster/Domain/UseCase/Clip/DefaultDeleteClipUseCase.swift
  Clipster/Clipster/Domain/UseCase/Clip/DefaultVisitClipUseCase.swift
  Clipster/Clipster/Presentation/Scene/EditClip/Reactor/EditClipReactor.swift
  Clipster/Clipster/Presentation/Util/Mapper/ClipDisplayMapper.swift
Labels: feat, refactor

#518 폴더 없이도 클립이 저장될 수 있도록 변경
  Clipster/Clipster/App/DIContainer/DIContainer.swift
  Clipster/Clipster/Data/Persistence/DefaultClipStorage.swift
  Clipster/Clipster/Data/Protocol/Persistence/ClipStorage.swift
  Clipster/Clipster/Data/Repository/Clip/DefaultClipRepository.swift
  Clipster/Clipster/Domain/Model/Entity/Clip.swift
  Clipster/Clipster/Domain/Protocol/Repository/Clip/ClipRepository.swift
  Clipster/Clipster/Domain/Protocol/UseCase/Clip/FetchTopLevelClipsUseCase.swift
  Clipster/Clipster/Domain/UseCase/Clip/DefaultFetchTopLevelClipsUseCase.swift
  Clipster/Clipster/Presentation/Scene/ClipDetail/Reactor/ClipDetailReactor.swift
  Clipster/Clipster/Presentation/Scene/EditClip/Reactor/EditClipReactor.swift
Labels: feat

#524 홈화면에 클립 섹션 추가
  Clipster/Clipster/App/DIContainer/DIContainer.swift
  Clipster/Clipster/Presentation/Model/HomeDisplay.swift
  Clipster/Clipster/Presentation/Scene/Home/Reactor/HomeReactor.swift
  Clipster/Clipster/Presentation/Scene/Home/Subview/View/HomeView.swift
Labels: feat

#522 FA버튼 구현
  Clipster/Clipster/Presentation/Scene/Common/Button/AddFAButton.swift
  Clipster/Clipster/Presentation/Scene/Folder/Subview/View/FolderView.swift
  Clipster/Clipster/Presentation/Scene/Home/Subview/View/HomeView.swift
Labels: feat

#526 다른 모든 앱에서 공유하기 버튼으로 담담 보이도록 수정
  Clipster/Clipster/App/Derived/Info.plist
  Clipster/Clipster/Data/Repository/URL/DefaultURLRepository.swift
  Clipster/Clipster/Domain/UseCase/URL/DefaultParseURLUseCase.swift
  Clipster/ShareExtension/Info.plist
  Clipster/ShareExtension/ShareViewController.swift
Labels: feat, refactor, fix, chore

#533 홈에 클립 저장 가능하도록 변경
  Clipster/Clipster/Data/Model/Persistence/Clipster.xcdatamodeld/Clipster3.xcdatamodel/contents
  Clipster/Clipster/Data/Util/Mapper/DomainMapper.swift
  Clipster/Clipster/Presentation/Scene/EditClip/Reactor/EditClipReactor.swift
  Clipster/Clipster/Presentation/Scene/EditClip/ViewController/EditClipViewController.swift
Labels: feat, refactor, chore

#536 홈 클립 삭제 후 Reload 및 섹션 헤더 재사용 Hidden 처리
  Clipster/Clipster/Presentation/Scene/Common/Cell/CollectionHeaderView.swift
  Clipster/Clipster/Presentation/Scene/Home/Reactor/HomeReactor.swift
Labels: fix

#540 클립 상세 화면에서 홈 보이도록 수정
  Clipster/Clipster/Presentation/Scene/ClipDetail/Reactor/ClipDetailReactor.swift
  Clipster/Clipster/Presentation/Scene/ClipDetail/Subview/View/ClipDetailView.swift
  Clipster/Clipster/Presentation/Scene/ClipDetail/ViewController/ClipDetailViewController.swift
Labels: fix
