Repository TeamSaltshaker/DamDam, pull requests merged in 2025-07, with the labels that each got.

#544 테스트 코드 클립 섹션 추가 대응
  Clipster/ClipsterTests/Presentation/Mock/UseCase/Clip/MockFetchTopLevelClipsUseCase.swift
  Clipster/ClipsterTests/Presentation/Reactor/HomeReactorTests.swift
Labels: test

#546 In-memory 캐시 초기 구현
  Clipster/Clipster/App/DIContainer/DIContainer.swift
  Clipster/Clipster/App/Source/SceneDelegate.swift
  Clipster/Clipster/Data/Model/Cache/FolderClipCache.swift
  Clipster/Clipster/Data/Repository/Clip/DefaultClipRepository.swift
  Clipster/Clipster/Data/Repository/Folder/DefaultFolderRepository.swift
  Clipster/Clipster/Domain/Error/DomainError.swift
  Clipster/Clipster/Domain/Protocol/Repository/Clip/ClipRepository.swift
  Clipster/Clipster/Domain/UseCase/Clip/DefaultCreateClipUseCase.swift
Labels: feat

#558 Repository가 cache를 optional로 가지도록 변경
  Clipster/Clipster/Data/Repository/Clip/DefaultClipRepository.swift
  Clipster/Clipster/Data/Repository/Folder/DefaultFolderRepository.swift
Labels: refactor

#550 마이페이지 UI 구현
  Clipster/Clipster/Domain/Model/VO/ClipSortOption.swift
  Clipster/Clipster/Domain/Model/VO/FolderSortOption.swift
  Clipster/Clipster/Domain/Model/VO/SavePathOption.swift
  Clipster/Clipster/Domain/Model/VO/ThemeOption.swift
  Clipster/Clipster/Presentation/Resource/Icon.xcassets/AppleIcon.imageset/AppleIcon.svg
  Clipster/Clipster/Presentation/Resource/Icon.xcassets/AppleIcon.imageset/Contents.json
  Clipster/Clipster/Presentation/Resource/Icon.xcassets/ChevronLightDown.imageset/ChevronLightDown.svg
  Clipster/Clipster/Presentation/Resource/Icon.xcassets/ChevronLightDown.imageset/Contents.json
  Clipster/Clipster/Presentation/Resource/Icon.xcassets/ChevronLightUp.imageset/ChevronLightUp.svg
  Clipster/Clipster/Presentation/Resource/Icon.xcassets/ChevronLightUp.imageset/Contents.json
  Clipster/Clipster/Presentation/Resource/Icon.xcassets/GoogleIcon.imageset/Contents.json
  Clipster/Clipster/Presentation/Resource/Icon.xcassets/GoogleIcon.imageset/GoogleIcon.svg
  Clipster/Clipster/Presentation/Scene/Common/Cell/CollectionHeaderView.swift
  Clipster/Clipster/Presentation/Scene/MyPage/Model/Account/AccountItem.swift
  Clipster/Clipster/Presentation/Scene/MyPage/Model/Chevron/ChevronItem.swift
  Clipster/Clipster/Presentation/Scene/MyPage/Model/Detail/DetailItem.swift
  Clipster/Clipster/Presentation/Scene/MyPage/Model/Detail/SavePathOption+Extension.swift
  Clipster/Clipster/Presentation/Scene/MyPage/Model/Detail/ThemeOption+Extension.swift
  Clipster/Clipster/Presentation/Scene/MyPage/Model/Dropdown/ClipSortOption+Extension.swift
  Clipster/Clipster/Presentation/Scene/MyPage/Model/Dropdown/DropdownItem.swift
  Clipster/Clipster/Presentation/Scene/MyPage/Model/Dropdown/FolderSortOption+Extension.swift
  Clipster/Clipster/Presentation/Scene/MyPage/Model/Dropdown/SortDirection+Extension.swift
  Clipster/Clipster/Presentation/Scene/MyPage/Model/Dropdown/SortOption.swift
  Clipster/Clipster/Presentation/Scene/MyPage/Model/Item/MyPageItem.swift
  Clipster/Clipster/Presentation/Scene/MyPage/Model/Item/MyPageSection.swift
  Clipster/Clipster/Presentation/Scene/MyPage/Model/Item/MyPageSectionModel.swift
  Clipster/Clipster/Presentation/Scene/MyPage/Model/Login/LoginType+Extension.swift
  Clipster/Clipster/Presentation/Scene/MyPage/SubView/Cell/LoginCell.swift
  Clipster/Clipster/Presentation/Scene/MyPage/SubView/Cell/SectionBackgroundView.swift
  Clipster/Clipster/Presentation/Scene/MyPage/SubView/Cell/SettingCell.swift
  Clipster/Clipster/Presentation/Scene/MyPage/SubView/View/MyPageView.swift
Labels: feat

#557 클립 상세화면 날짜 추가
  Clipster/Clipster/Presentation/Model/ClipDisplay.swift
  Clipster/Clipster/Presentation/Scene/ClipDetail/Subview/View/ClipDetailView.swift
  Clipster/Clipster/Presentation/Util/Mapper/ClipDisplayMapper.swift
Labels: feat

#555 앱 설정 및 회원관리 UseCase 구현
  Clipster/Clipster/Domain/Protocol/UseCase/Auth/CheckLoginStatusUseCase.swift
  Clipster/Clipster/Domain/Protocol/UseCase/Auth/LogoutUseCase.swift
  Clipster/Clipster/Domain/Protocol/UseCase/Auth/WithdrawUseCase.swift
  Clipster/Clipster/Domain/Protocol/UseCase/Setting/FetchClipSortOptionUseCase.swift
  Clipster/Clipster/Domain/Protocol/UseCase/Setting/FetchFolderSortOptionUseCase.swift
  Clipster/Clipster/Domain/Protocol/UseCase/Setting/FetchSavePathLayoutOptionUseCase.swift
  Clipster/Clipster/Domain/Protocol/UseCase/Setting/FetchThemeOptionUseCase.swift
  Clipster/Clipster/Domain/Protocol/UseCase/Setting/SaveClipSortOptionUseCase.swift
  Clipster/Clipster/Domain/Protocol/UseCase/Setting/SaveFolderSortOptionUseCase.swift
  Clipster/Clipster/Domain/Protocol/UseCase/Setting/SaveSavePathLayoutOptionUseCase.swift
  Clipster/Clipster/Domain/Protocol/UseCase/Setting/SaveThemeOptionUseCase.swift
  Clipster/Clipster/Domain/UseCase/Auth/DefaultCheckLoginStatusUseCase.swift
  Clipster/Clipster/Domain/UseCase/Auth/DefaultLogoutUseCase.swift
  Clipster/Clipster/Domain/UseCase/Auth/DefaultWithdrawUseCase.swift
  Clipster/Clipster/Domain/UseCase/Setting/DefaultFetchClipSortOptionUseCase.swift
  Clipster/Clipster/Domain/UseCase/Setting/DefaultFetchFolderSortOptionUseCase.swift
  Clipster/Clipster/Domain/UseCase/Setting/DefaultFetchSavePathLayoutOptionUseCase.swift
  Clipster/Clipster/Domain/UseCase/Setting/DefaultFetchThemeOptionUseCase.swift
  Clipster/Clipster/Domain/UseCase/Setting/DefaultSaveClipSortOptionUseCase.swift
  Clipster/Clipster/Domain/UseCase/Setting/DefaultSaveFolderSortOptionUseCase.swift
  Clipster/Clipster/Domain/UseCase/Setting/DefaultSaveSavePathLayoutOptionUseCase.swift
  Clipster/Clipster/Domain/UseCase/Setting/DefaultSaveThemeOptionUseCase.swift
Labels: feat

#569 SceneDelegate에서 UserDefaults 갖도록 수정
  Clipster/Clipster/App/DIContainer/DIContainer.swift
  Clipster/Clipster/App/Source/SceneDelegate.swift
Labels: refactor

#564 최근 검색어 UseCase 구현
  Clipster/Clipster/App/DIContainer/DIContainer.swift
  Clipster/Clipster/Domain/Protocol/UseCase/Query/DeleteAllRecentQueriesUseCase.swift
  Clipster/Clipster/Domain/Protocol/UseCase/Query/DeleteRecentQueryUseCase.swift
  Clipster/Clipster/Domain/Protocol/UseCase/Query/FetchRecentQueriesUseCase.swift
  Clipster/Clipster/Domain/Protocol/UseCase/Query/SaveRecentQueryUseCase.swift
  Clipster/Clipster/Domain/UseCase/Query/DefaultDeleteAllRecentQueriesUseCase.swift
  Clipster/Clipster/Domain/UseCase/Query/DefaultDeleteRecentQueryUseCase.swift
  Clipster/Clipster/Domain/UseCase/Query/DefaultFetchRecentQueriesUseCase.swift
  Clipster/Clipster/Domain/UseCase/Query/DefaultSaveRecentQueryUseCase.swift
Labels: feat

#566 전체 폴더 및 클립 조회 구현
  Clipster/Clipster/Data/Persistence/DefaultClipStorage.swift
  Clipster/Clipster/Data/Persistence/DefaultFolderStorage.swift
  Clipster/Clipster/Data/Protocol/Persistence/ClipStorage.swift
  Clipster/Clipster/Data/Protocol/Persistence/FolderStorage.swift
  Clipster/Clipster/Data/Repository/Clip/DefaultClipRepository.swift
  Clipster/Clipster/Data/Repository/Folder/DefaultFolderRepository.swift
  Clipster/Clipster/Domain/Protocol/Repository/Clip/ClipRepository.swift
  Clipster/Clipster/Domain/Protocol/Repository/Folder/FolderRepository.swift
  Clipster/Clipster/Domain/UseCase/Clip/DefaultFetchAllClipsUseCase.swift
  Clipster/Clipster/Domain/UseCase/Folder/DefaultFetchAllFoldersUseCase.swift
Labels: feat

#600 User, UserDTO 타겟 멤버십 수정
  Clipster/Clipster.xcodeproj/project.pbxproj
Labels: fix

#587 EditClipView - Share Extension 관련 로직 제거
  Clipster/Clipster/App/DIContainer/DIContainer.swift
  Clipster/Clipster/Presentation/Scene/EditClip/Reactor/EditClipReactor.swift
  Clipster/Clipster/Presentation/Scene/EditClip/ViewController/EditClipViewController.swift
Labels: refactor

#586 폴더 선택 후 상위 폴더를 접어도 타이틀에 선택된 폴더 이름이 보이도록 수정
  Clipster/Clipster/Presentation/Scene/FolderSelector/Reactor/FolderSelectorReactor.swift
Labels: fix

#581 UseCase 테스트 코드 목 데이터 사용하도록 수정
  Clipster/ClipsterTests/Domain/UseCase/Folder/FilterSubfoldersUseCaseTests.swift
  Clipster/ClipsterTests/Domain/UseCase/Folder/FindFolderPathUseCaseTests.swift
Labels: test

#604 Blue400 색상을 Blue600으로 변경
  Clipster/Clipster/Presentation/Scene/Common/Button/ConfirmButton.swift
  Clipster/Clipster/Presentation/Scene/Common/Button/SaveButton.swift
  Clipster/Clipster/Presentation/Scene/Common/Button/SelectButton.swift
  Clipster/Clipster/Presentation/Scene/Common/Cell/ClipListCell.swift
  Clipster/Clipster/Presentation/Scene/Home/Subview/Cell/ClipGirdCell.swift
  Clipster/Clipster/Presentation/Scene/MyPage/Model/Item/MyPageItem.swift
Labels: fix

#573 MyPageReactor 구현 및 일부 이벤트 바인딩
  Clipster/Clipster/App/DIContainer/DIContainer.swift
  Clipster/Clipster/Presentation/Coordinator/MyPage/MyPageCoordinator.swift
  Clipster/Clipster/Presentation/Coordinator/TabBar/TabBarCoordinator.swift
  Clipster/Clipster/Presentation/Scene/MyPage/Model/Dropdown/ClipSortOption+Extension.swift
  Clipster/Clipster/Presentation/Scene/MyPage/Model/Dropdown/FolderSortOption+Extension.swift
  Clipster/Clipster/Presentation/Scene/MyPage/Model/Mail/InquiryMail.swift
  Clipster/Clipster/Presentation/Scene/MyPage/Reactor/MyPageReactor.swift
  Clipster/Clipster/Presentation/Scene/MyPage/SubView/View/MyPageView.swift
  Clipster/Clipster/Presentation/Scene/MyPage/ViewController/MyPageViewController.swift
Labels: feat

#616 EditClipView 진입 시 클립보드 감지
  Clipster/Clipster/Presentation/Scene/EditClip/Reactor/EditClipReactor.swift
  Clipster/Clipster/Presentation/Scene/EditClip/ViewController/EditClipViewController.swift
Labels: feat

#617 클립/폴더 셸 디자인 수정 사항 반영 및 FA버튼 크기 변경
  Clipster/Clipster/Presentation/Model/ClipDisplay.swift
  Clipster/Clipster/Presentation/Scene/Common/Button/AddFAButton.swift
  Clipster/Clipster/Presentation/Scene/Common/Cell/ClipListCell.swift
  Clipster/Clipster/Presentation/Scene/Common/Cell/FolderListCell.swift
  Clipster/Clipster/Presentation/Scene/Folder/Subview/View/FolderView.swift
  Clipster/Clipster/Presentation/Scene/Home/Subview/View/HomeView.swift
  Clipster/Clipster/Presentation/Util/Mapper/ClipDisplayMapper.swift
Labels: fix

#582 FolderSelector 테스트 추가
  Clipster/Clipster/Presentation/Scene/FolderSelector/Reactor/FolderSelectorReactor.swift
  Clipster/ClipsterTests/Presentation/Mock/UseCase/Folder/MockFetchSavePathLayoutOptionUseCase.swift
  Clipster/ClipsterTests/Presentation/Mock/UseCase/Folder/MockFilterSubfoldersUseCase.swift
  Clipster/ClipsterTests/Presentation/Mock/UseCase/Folder/MockFindFolderPathUseCase.swift
  Clipster/ClipsterTests/Presentation/Reactor/FolderSelectorReactorTests.swift
Labels: test

#596 SearchClipsUseCase 테스트 추가
  Clipster/ClipsterTests/Domain/UseCase/Clip/SearchClipsUseCaseTests.swift
Labels: test

#598 SortFoldersUseCase 테스트 추가
  Clipster/ClipsterTests/Domain/UseCase/Folder/SortFoldersUseCaseTests.swift
Labels: test

#602 SortClipsUseCase 테스트 추가
  Clipster/ClipsterTests/Domain/UseCase/Clip/SortClipsUseCaseTests.swift
  Clipster/ClipsterTests/Presentation/Mock/Entity/MockClip.swift
Labels: test

#609 Search~UseCase 공백 제거한 문자열 사용하도록 수정
  Clipster/Clipster/Domain/UseCase/Clip/DefaultSearchClipsUseCase.swift
  Clipster/Clipster/Domain/UseCase/Folder/DefaultSearchFoldersUseCase.swift
Labels: fix

#579 테마 선택 모달 구현
  Clipster/Clipster/App/DIContainer/DIContainer.swift
  Clipster/Clipster/Presentation/Coordinator/MyPage/MyPageCoordinator.swift
  Clipster/Clipster/Presentation/Protocol/SelectableOption.swift
  Clipster/Clipster/Presentation/Resource/Icon.xcassets/RadioSelected.imageset/Contents.json
  Clipster/Clipster/Presentation/Resource/Icon.xcassets/RadioSelected.imageset/RadioSelected.svg
  Clipster/Clipster/Presentation/Resource/Icon.xcassets/RadioUnselected.imageset/Contents.json
  Clipster/Clipster/Presentation/Resource/Icon.xcassets/RadioUnselected.imageset/RadioUnselected.svg
  Clipster/Clipster/Presentation/Scene/Common/Cell/RadioCell.swift
  Clipster/Clipster/Presentation/Scene/MyPage/Model/Detail/ThemeOption+Extension.swift
  Clipster/Clipster/Presentation/Scene/MyPage/Reactor/MyPageReactor.swift
  Clipster/Clipster/Presentation/Scene/MyPage/ViewController/MyPageViewController.swift
  Clipster/Clipster/Presentation/Scene/SingleOptionSelector/ViewController/SingleOptionSelectorViewController.swift
Labels: feat

#611 최근 방문 클립을 가져올 때 정렬하도록 수정
  Clipster/Clipster/Domain/UseCase/Clip/DefaultFetchRecentVisitedClipsUseCase.swift
Labels: fix

#624 정렬 기본값 수정 및 홈화면 정렬 적용
  Clipster/Clipster/App/DIContainer/DIContainer.swift
  Clipster/Clipster/Domain/UseCase/Setting/DefaultFetchClipSortOptionUseCase.swift
  Clipster/Clipster/Domain/UseCase/Setting/DefaultFetchFolderSortOptionUseCase.swift
  Clipster/Clipster/Domain/UseCase/Setting/DefaultFetchSavePathLayoutOptionUseCase.swift
  Clipster/Clipster/Presentation/Scene/Home/Reactor/HomeReactor.swift
Labels: feat

#625 FolderView 폴더, 클립 정렬 적용
  Clipster/Clipster/App/DIContainer/DIContainer.swift
  Clipster/Clipster/Presentation/Scene/Folder/Reactor/FolderReactor.swift
Labels: feat, refactor

#631 온보딩 화면 구현
  Clipster/Clipster/App/Coordinator/App/AppCoordinator.swift
  Clipster/Clipster/Presentation/Resource/Icon.xcassets/OnboardingAdd.imageset/Contents.json
  Clipster/Clipster/Presentation/Resource/Icon.xcassets/OnboardingAdd.imageset/OnboardingAdd.png
  Clipster/Clipster/Presentation/Resource/Icon.xcassets/OnboardingFolder.imageset/Contents.json
  Clipster/Clipster/Presentation/Resource/Icon.xcassets/OnboardingFolder.imageset/OnboardingFolder.png
  Clipster/Clipster/Presentation/Resource/Icon.xcassets/OnboardingLongTap.imageset/Contents.json
  Clipster/Clipster/Presentation/Resource/Icon.xcassets/OnboardingLongTap.imageset/OnboardingLongTap.png
  Clipster/Clipster/Presentation/Resource/Icon.xcassets/OnboardingShare.imageset/Contents.json
  Clipster/Clipster/Presentation/Resource/Icon.xcassets/OnboardingShare.imageset/OnboardingShare.png
  Clipster/Clipster/Presentation/Resource/Icon.xcassets/OnboardingUnvisited.imageset/Contents.json
  Clipster/Clipster/Presentation/Resource/Icon.xcassets/OnboardingUnvisited.imageset/OnboardingUnvisited.png
  Clipster/Clipster/Presentation/Resource/Icon.xcassets/OnboardingValidation.imageset/Contents.json
  Clipster/Clipster/Presentation/Resource/Icon.xcassets/OnboardingValidation.imageset/OnboardingValidation.png
  Clipster/Clipster/Presentation/Scene/Onboarding/Model/OnboardingItem.swift
  Clipster/Clipster/Presentation/Scene/Onboarding/SubView/Cell/OnboardingCell.swift
  Clipster/Clipster/Presentation/Scene/Onboarding/ViewController/OnboardingViewController.swift
Labels: feat

#627 FolderReactor 변경에 따른 테스트 수정
  Clipster/Clipster/App/DIContainer/DIContainer.swift
  Clipster/ClipsterTests/Presentation/Reactor/FolderReactorTests.swift
Labels: test

#592 저장 경로 보기 선택 모달 구현
  Clipster/Clipster/App/DIContainer/DIContainer.swift
  Clipster/Clipster/Presentation/Coordinator/MyPage/MyPageCoordinator.swift
  Clipster/Clipster/Presentation/Resource/Icon.xcassets/SavePathLayoutAccordion.imageset/Contents.json
  Clipster/Clipster/Presentation/Resource/Icon.xcassets/SavePathLayoutAccordion.imageset/SavePathLayoutAccordion.svg
  Clipster/Clipster/Presentation/Resource/Icon.xcassets/SavePathLayoutDirectory.imageset/Contents.json
  Clipster/Clipster/Presentation/Resource/Icon.xcassets/SavePathLayoutDirectory.imageset/SavePathLayoutDirectory.svg
  Clipster/Clipster/Presentation/Scene/Common/View/RadioLabelView.swift
  Clipster/Clipster/Presentation/Scene/MyPage/Reactor/MyPageReactor.swift
  Clipster/Clipster/Presentation/Scene/MyPage/ViewController/MyPageViewController.swift
  Clipster/Clipster/Presentation/Scene/SavePathOptionSelector/SavePathSelectorViewController.swift
  Clipster/Clipster/Presentation/Scene/SavePathOptionSelector/SubView/View/SavePathLayoutRadioImageView.swift
  Clipster/Clipster/Presentation/Scene/SavePathOptionSelector/SubView/View/SavePathOptionSelectorView.swift
  Clipster/Clipster/Presentation/Scene/SingleOptionSelector/SubView/Cell/RadioCell.swift
  Clipster/Clipster/Presentation/Scene/SingleOptionSelector/ViewController/SingleOptionSelectorViewController.swift
Labels: feat

#634 마이페이지 화면 로그인 기능 적용 및 닉네임 변경 모달 구현
  Clipster/Clipster/App/DIContainer/DIContainer.swift
  Clipster/Clipster/Presentation/Coordinator/MyPage/MyPageCoordinator.swift
  Clipster/Clipster/Presentation/Scene/EditNickname/SubView/View/EditNicknameView.swift
  Clipster/Clipster/Presentation/Scene/EditNickname/ViewController/EditNicknameViewController.swift
  Clipster/Clipster/Presentation/Scene/MyPage/Model/Item/MyPageSection.swift
  Clipster/Clipster/Presentation/Scene/MyPage/Reactor/MyPageReactor.swift
  Clipster/Clipster/Presentation/Scene/MyPage/SubView/View/MyPageView.swift
  Clipster/Clipster/Presentation/Scene/MyPage/ViewController/MyPageViewController.swift
Labels: feat

#633 공통 네비게이션 뷰 레이아웃 경고 해결
  Clipster/Clipster/Presentation/Scene/Common/View/CommonNavigationView.swift
Labels: fix

#640 마이페이지 섹션 로그인 기능 보류 대응
  Clipster/Clipster/Presentation/Scene/MyPage/Reactor/MyPageReactor.swift
Labels: fix

#641 Supabase Database 구현
  Clipster/Clipster.xcodeproj/project.pbxproj
  Clipster/Clipster/Data/Error/DatabaseError.swift
  Clipster/Clipster/Data/Model/Network/ClipDTO.swift
  Clipster/Clipster/Data/Model/Network/FolderDTO.swift
  Clipster/Clipster/Data/Network/Database/DefaultClipService.swift
  Clipster/Clipster/Data/Network/Database/DefaultFolderService.swift
  Clipster/Clipster/Data/Protocol/Network/ClipService.swift
  Clipster/Clipster/Data/Protocol/Network/FolderService.swift
  Clipster/Clipster/Data/Protocol/Network/SocialLoginService.swift
Labels: feat, refactor

#647 Share Extension 네비게이션 안 보이는 문제 수정
  Clipster/ShareExtension/ViewController/ShareViewController.swift
Labels: fix

#654 v1.2.0 릴리즈
  Clipster/Clipster.xcodeproj/project.pbxproj
  Clipster/Clipster/Presentation/Resource/Icon.xcassets/OnboardingAdd.imageset/OnboardingAdd.png
  Clipster/Clipster/Presentation/Resource/Icon.xcassets/OnboardingFolder.imageset/OnboardingFolder.png
  Clipster/Clipster/Presentation/Resource/Icon.xcassets/OnboardingLongTap.imageset/OnboardingLongTap.png
  Clipster/Clipster/Presentation/Resource/Icon.xcassets/OnboardingUnvisited.imageset/OnboardingUnvisited.png
  Clipster/Clipster/Presentation/Resource/Icon.xcassets/OnboardingValidation.imageset/OnboardingValidation.png
  Clipster/Clipster/Presentation/Scene/Folder/Subview/View/FolderView.swift
  Clipster/Clipster/Presentation/Scene/Home/Subview/View/HomeView.swift
  Clipster/Clipster/Presentation/Scene/Onboarding/ViewController/OnboardingViewController.swift
  Clipster/Clipster/Presentation/Scene/Search/ViewController/SearchViewController.swift
  Clipster/Clipster/Presentation/Scene/UnvisitedClipList/SubView/View/UnvisitedClipListView.swift
  Clipster/ShareExtension/ViewController/ShareViewController.swift
Labels: fix, chore

#660 ShareExtension에서 메인 앱 진입 관련 로직 제거
  Clipster/Clipster/App/Coordinator/App/AppCoordinator.swift
  Clipster/Clipster/App/DIContainer/DIContainer.swift
  Clipster/Clipster/App/Source/SceneDelegate.swift
  Clipster/Clipster/Presentation/Coordinator/Home/HomeCoordinator.swift
  Clipster/Clipster/Presentation/Scene/EditClip/Reactor/EditClipReactor.swift
Labels: refactor

#655 삭제된 항목을 item count에 포함시키는 이슈 수정
  Clipster/Clipster/Data/Persistence/DefaultClipStorage.swift
  Clipster/Clipster/Data/Persistence/DefaultFolderStorage.swift
  Clipster/Clipster/Domain/UseCase/Folder/DefaultFetchFolderUseCase.swift
  Clipster/Clipster/Domain/UseCase/Folder/DefaultFetchTopLevelFoldersUseCase.swift
Labels: refactor, fix

#674 v1.2.1 릴리즈
  Clipster/Clipster.xcodeproj/project.pbxproj
Labels: chore

#664 EditClipReactor Derived State 도입 리팩토링
  Clipster/Clipster.xcodeproj/project.pbxproj
  Clipster/Clipster/Presentation/Model/ParseResultType.swift
  Clipster/Clipster/Presentation/Scene/EditClip/Reactor/EditClipReactor.swift
  Clipster/ShareExtension/Reactor/ShareReactor.swift
Labels: refactor

#675 UnvisitedClipListReactor 테스트 코드 작성
  Clipster/ClipsterTests/Presentation/Reactor/UnvisitedClipListReactorTests.swift
Labels: test

#681 TargetMembership 수정
  Clipster/Clipster.xcodeproj/project.pbxproj
  Clipster/ShareExtension/Reactor/ShareReactor.swift
Labels: fix

#682 FolderReactor에 Derived State 적용
  Clipster/Clipster/Presentation/Scene/Folder/Reactor/FolderReactor.swift
Labels: refactor

#684 다크모드 색상 재설정
  Clipster/Clipster/Presentation/Resource/Color.xcassets/AppTheme/AppPrimary.colorset/Contents.json
  Clipster/Clipster/Presentation/Resource/Color.xcassets/Blue/Blue650.colorset/Contents.json
  Clipster/Clipster/Presentation/Resource/Icon.xcassets/CheckBlue.imageset/Contents.json
  Clipster/Clipster/Presentation/Resource/Icon.xcassets/CheckBlue.imageset/check-blue-dark.svg
  Clipster/Clipster/Presentation/Resource/Icon.xcassets/ChevronDownBlue.imageset/Contents.json
  Clipster/Clipster/Presentation/Resource/Icon.xcassets/ChevronDownBlue.imageset/chevron-down-blue-dark.svg
  Clipster/Clipster/Presentation/Resource/Icon.xcassets/ChevronRightBlue.imageset/Contents.json
  Clipster/Clipster/Presentation/Resource/Icon.xcassets/ChevronRightBlue.imageset/chevron-right-blue-dark.svg
  Clipster/Clipster/Presentation/Resource/Icon.xcassets/ChevronUpBlue.imageset/Contents.json
  Clipster/Clipster/Presentation/Resource/Icon.xcassets/ChevronUpBlue.imageset/chevron-up-blue-dark.svg
  Clipster/Clipster/Presentation/Resource/Icon.xcassets/FolderBlue.imageset/Contents.json
  Clipster/Clipster/Presentation/Resource/Icon.xcassets/FolderBlue.imageset/folder-blue-dark.svg
  Clipster/Clipster/Presentation/Resource/Icon.xcassets/HomeBlue.imageset/Contents.json
  Clipster/Clipster/Presentation/Resource/Icon.xcassets/HomeBlue.imageset/home-blue-dark.svg
  Clipster/Clipster/Presentation/Resource/Icon.xcassets/RadioSelected.imageset/Contents.json
  Clipster/Clipster/Presentation/Resource/Icon.xcassets/RadioSelected.imageset/radio-selected-blue-dark.svg
Labels: feat
